<a href="https://colab.research.google.com/github/luisantoniounocc/PRACTICA_CALIFICADA/blob/main/PRACTICA_CALIFICADA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EJERCICIO 01:
• Crea un vector de números enteros del 1 al 20.
• Crea una matriz de 3x3 con valores aleatorios entre 0 y 1.
• Redimensiona una matriz de 4x4 a una matriz de 2x8.
• Crea un array de 10 números equidistantes entre 0 y 1.
• Concatena dos vectores vertical y horizontalmente. (concatenate)


1.1

In [9]:
import numpy as np

vector = np.arange(1, 21)
print("Vector del 1 al 20:")
print(vector)

Vector del 1 al 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


1.2

In [ ]:
matriz_3x3 = np.random.rand(3, 3)
print("\nMatriz 3x3 aleatoria:")
print(matriz_3x3)

1.3

In [ ]:
matriz_4x4 = np.random.rand(4, 4)
matriz_2x8 = matriz_4x4.reshape(2, 8)
print("\nMatriz 4x4 original:")
print(matriz_4x4)
print("\nMatriz redimensionada 2x8:")
print(matriz_2x8)

1.4

In [ ]:
array_10 = np.linspace(0, 1, 10)
print("\nArray de 10 números equidistantes entre 0 y 1:")
print(array_10)

1.5

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Concatenación horizontal (1D)
concat_horizontal = np.concatenate((v1, v2))
print("\nConcatenación horizontal:")
print(concat_horizontal)

# Concatenación vertical (convertir vectores a 2D)
v1_2d = v1.reshape(1, -1)
v2_2d = v2.reshape(1, -1)
concat_vertical = np.concatenate((v1_2d, v2_2d), axis=0)
print("\nConcatenación vertical:")
print(concat_vertical)

EJERCICIO 02: Resolver las siguientes operaciones:
Calcula la suma, resta, multiplicación y división de dos vectores.
Calcula la media, mediana y desviación estándar de un vector.
Normaliza un vector dividiendo cada elemento por el valor máximo.
Encuentra el índice del valor máximo y mínimo en un vector.
Realiza una multiplicación matricial entre dos matrices 3x3.

2.1

In [11]:
import numpy as np

v1 = np.array([10, 20, 30, 40, 50])
v2 = np.array([2, 4, 6, 8, 10])

print("Suma:", v1 + v2)
print("Resta:", v1 - v2)
print("Multiplicación:", v1 * v2)
print("División:", v1 / v2)

Suma: [12 24 36 48 60]
Resta: [ 8 16 24 32 40]
Multiplicación: [ 20  80 180 320 500]
División: [5. 5. 5. 5. 5.]


2.2

In [ ]:
print("Media:", np.mean(v1))
print("Mediana:", np.median(v1))
print("Desviación estándar:", np.std(v1))

2.3

In [10]:
v_norm = v1 / np.max(v1)
print("Vector normalizado:", v_norm)

Vector normalizado: [0.2 0.4 0.6 0.8 1. ]


2.4

In [ ]:
print("Índice máximo:", np.argmax(v1))
print("Índice mínimo:", np.argmin(v1))

2.5

In [ ]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
m2 = np.array([[9, 8, 7],
               [6, 5, 4],
               [3, 2, 1]])

producto = np.matmul(m1, m2)
print("Multiplicación matricial:\n", producto)

EJERCICIO 03: Resolver con numpy los siguientes casos:
Selecciona los elementos pares de un vector de números enteros.
Filtra los valores mayores que 5 en un vector
Filtra los valores iguales a cero
Filtra los valores negativos
Aplicar la media a los valores mayores de 50.


3.1

In [12]:
import numpy as np
vector = np.array([0, 2, 3, 4, 6, 7, 8, 10, 12, 15, 50, 60, 70, -5, -10, 0])
pares = vector[vector % 2 == 0]
print("Elementos pares:", pares)

Elementos pares: [  0   2   4   6   8  10  12  50  60  70 -10   0]


3.2

In [13]:
mayores_5 = vector[vector > 5]
print("Valores mayores que 5:", mayores_5)

Valores mayores que 5: [ 6  7  8 10 12 15 50 60 70]


3.3

In [14]:
iguales_cero = vector[vector == 0]
print("Valores iguales a cero:", iguales_cero)

Valores iguales a cero: [0 0]


3.4

In [ ]:
negativos = vector[vector < 0]
print("Valores negativos:", negativos)

3.5

In [15]:
mayores_50 = vector[vector > 50]
media_mayores_50 = np.mean(mayores_50) if mayores_50.size > 0 else None
print("Media de valores mayores que 50:", media_mayores_50)

Media de valores mayores que 50: 65.0


EJERCICIO 04: 4. Resolver con numpy los siguientes casos:
Crea un vector de 10 elementos y reemplaza todos los valores mayores que 5 con 0.
• Combina dos vectores booleanos utilizando las operaciones & (AND) y | (OR).
• Cuenta la cantidad de valores en un vector que son múltiplos de 3.
• Encuentra los índices de los elementos no nulos en un vector. (np.nonzero) Comprueba si todos los elementos en un array son mayores que un valor específico digitado por el usuario.

4.1

In [16]:
import numpy as np

v = np.array([1, 6, 3, 8, 5, 10, 2, 7, 4, 9])
v[v > 5] = 0
print("Vector con valores > 5 reemplazados por 0:")
print(v)

Vector con valores > 5 reemplazados por 0:
[1 0 3 0 5 0 2 0 4 0]


4.2

In [ ]:
b1 = np.array([True, False, True, False])
b2 = np.array([True, True, False, False])

print("AND:", b1 & b2)
print("OR:", b1 | b2)

4.3

In [ ]:
v2 = np.array([3, 6, 7, 9, 10, 12, 14, 15])
cantidad_multiplos_3 = np.sum(v2 % 3 == 0)
print("Cantidad de múltiplos de 3:", cantidad_multiplos_3)

4.4

In [ ]:
v3 = np.array([0, 1, 2, 0, 3, 0])
indices_no_nulos = np.nonzero(v3)[0]
print("Índices de elementos no nulos:", indices_no_nulos)

4.5

In [ ]:
valor = float(input("Introduce un valor para comparar: "))
arr = np.array([10, 15, 20, 25, 30])
todos_mayores = np.all(arr > valor)
print(f"¿Todos los elementos son mayores que {valor}? {todos_mayores}")

EJERCICIO 05: 5. Resolver con numpy los siguientes casos:
Calcula el cuadrado de cada elemento en un vector.
• Utiliza la función exponencial para elevar todos los elementos de un vector a la misma potencia.
• Encuentra los valores máximos y mínimos en cada fila de una matriz.
• Aplica la función sin a todos los elementos de un vector y almacena los resultados en otro vector.
• Realiza la transpuesta de una matriz 3x4.

5.1

In [16]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])
cuadrado = v ** 2
print("Cuadrado de cada elemento:", cuadrado)

5.2

In [ ]:
potencia = 3
exp_potencia = np.power(v, potencia)
print(f"Vector elevado a la potencia {potencia}:", exp_potencia)

5.3

In [17]:
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

maximos_filas = np.max(m, axis=1)
minimos_filas = np.min(m, axis=1)

print("Máximos por fila:", maximos_filas)
print("Mínimos por fila:", minimos_filas)

Máximos por fila: [ 4  8 12]
Mínimos por fila: [1 5 9]


5.4

In [ ]:
seno = np.sin(v)
print("Seno de cada elemento:", seno)

5.5

In [18]:
transpuesta = m.T
print("Matriz transpuesta (4x3):\n", transpuesta)


Matriz transpuesta (4x3):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Crea un DataFrame con las siguientes columnas: 'Nombre', 'Edad', 'Ciudad'. Añade al menos 10 registros.
• Del DataFrame creado, filtra a las personas que tienen más de 25 años. • A tu DataFrame, añade una nueva columna llamada 'Ingresos', rellénala con cualquier valor.
• Encuentra el promedio de la edad en tu DataFrame.
• Cuenta cuántas veces aparece cada ciudad en tu DataFrame.
• Agrupa tu DataFrame por 'Ciudad' y calcula el promedio de 'Edad' para cada ciudad. (groupby)
• Ordena tu DataFrame por 'Edad', de manera ascendente y luego descendente.

6.1

In [19]:
import pandas as pd

# Crear DataFrame
data = {'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Jorge', 'Elena', 'Pedro', 'Sofía', 'Raúl', 'Lucía'],
        'Edad': [23, 34, 29, 21, 40, 27, 33, 22, 30, 26],
        'Ciudad': ['Lima', 'Cusco', 'Lima', 'Arequipa', 'Cusco', 'Lima', 'Arequipa', 'Cusco', 'Lima', 'Arequipa']}

df = pd.DataFrame(data)

# Filtrar personas con edad mayor a 25
mayores_25 = df[df['Edad'] > 25]
print("Personas con más de 25 años:\n", mayores_25)


Personas con más de 25 años:
    Nombre  Edad    Ciudad
1    Luis    34     Cusco
2  Carlos    29      Lima
4   Jorge    40     Cusco
5   Elena    27      Lima
6   Pedro    33  Arequipa
8    Raúl    30      Lima
9   Lucía    26  Arequipa


6.2

In [ ]:
df['Ingresos'] = [1500, 2000, 1800, 1200, 2200, 1600, 1700, 1300, 1900, 1400]
print("DataFrame con columna 'Ingresos':\n", df)

6.3

In [ ]:
promedio_edad = df['Edad'].mean()
print("Promedio de edad:", promedio_edad)

6.4

In [ ]:
conteo_ciudades = df['Ciudad'].value_counts()
print("Cantidad por ciudad:\n", conteo_ciudades)


6.5

In [ ]:
promedio_por_ciudad = df.groupby('Ciudad')['Edad'].mean()
print("Promedio de edad por ciudad:\n", promedio_por_ciudad)


6.6

In [20]:
orden_asc = df.sort_values(by='Edad')
print("Ordenado por edad (ascendente):\n", orden_asc)

orden_desc = df.sort_values(by='Edad', ascending=False)
print("Ordenado por edad (descendente):\n", orden_desc)


Ordenado por edad (ascendente):
    Nombre  Edad    Ciudad
3   Marta    21  Arequipa
7   Sofía    22     Cusco
0     Ana    23      Lima
9   Lucía    26  Arequipa
5   Elena    27      Lima
2  Carlos    29      Lima
8    Raúl    30      Lima
6   Pedro    33  Arequipa
1    Luis    34     Cusco
4   Jorge    40     Cusco
Ordenado por edad (descendente):
    Nombre  Edad    Ciudad
4   Jorge    40     Cusco
1    Luis    34     Cusco
6   Pedro    33  Arequipa
8    Raúl    30      Lima
2  Carlos    29      Lima
5   Elena    27      Lima
9   Lucía    26  Arequipa
0     Ana    23      Lima
7   Sofía    22     Cusco
3   Marta    21  Arequipa


EJERCICIO 07: Del archivo adjunto realizar los siguientes filtros:
• Indicar cuantos son de la carrera de Ing. en sistemas
• Indicar cuantos son de la carrera de Ing. en derecho
• Indicar cuantos se inscribieron en el año 2015
• Indicar cuantos son del 1 y 2 semestre

Indicar cuantos son de la carrera de Ing. en sistemas

In [21]:
import pandas as pd
import numpy as np

df = pd.read_excel("universidad.xlsx")

# Normalizamos la columna 'Carrera'
df['Carrera'] = df['Carrera'].str.strip().str.lower()

# Convertimos a NumPy y filtramos
carreras = df['Carrera'].to_numpy()
filtro_sistemas = np.char.find(carreras.astype(str), 'ing. en sistemas') >= 0

# Resultado
print("Cantidad de estudiantes de Ing. en sistemas:", np.sum(filtro_sistemas))


Cantidad de estudiantes de Ing. en sistemas: 13


Indicar cuantos son de la carrera de Ing. en derecho

In [ ]:
filtro_derecho = np.char.find(carreras.astype(str), 'ing. en derecho') >= 0
# Resultado
print("Cantidad de estudiantes de Ing. en derecho:", np.sum(filtro_derecho))

Indicar cuantos se inscribieron en el año 2015

In [ ]:
df['Año Inscripción'] = pd.to_datetime(df['Inscripción']).dt.year
anios = df['Año Inscripción'].to_numpy()
filtro_2015 = anios == 2015
print("Cantidad de estudiantes inscritos en 2015:", np.sum(filtro_2015))

Indicar cuantos son del 1 y 2 semestre

In [ ]:
df['Semestre'] = pd.to_numeric(df['Semestre'], errors='coerce')
semestres = df['Semestre'].to_numpy()
filtro_1_2 = np.isin(semestres, [1, 2])
# Resultado
print("Cantidad de estudiantes en 1° y 2° semestre:", np.sum(filtro_1_2))
