<a href="https://colab.research.google.com/github/luisantoniounocc/PRACTICA_CALIFICADA/blob/main/PRACTICA_CALIFICADA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EJERCICIO 01:
• Crea un vector de números enteros del 1 al 20.
• Crea una matriz de 3x3 con valores aleatorios entre 0 y 1.
• Redimensiona una matriz de 4x4 a una matriz de 2x8.
• Crea un array de 10 números equidistantes entre 0 y 1.
• Concatena dos vectores vertical y horizontalmente. (concatenate)


1.1

In [2]:
import numpy as np

vector = np.arange(1, 21)
print("Vector del 1 al 20:")
print(vector)

Vector del 1 al 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


1.2

In [3]:
matriz_3x3 = np.random.rand(3, 3)
print("\nMatriz 3x3 aleatoria:")
print(matriz_3x3)


Matriz 3x3 aleatoria:
[[3.50867237e-01 8.92043507e-01 4.20274342e-02]
 [4.45045344e-01 4.20388766e-01 3.95402617e-04]
 [3.48382163e-02 2.48369376e-01 5.56824889e-01]]


1.3

In [4]:
matriz_4x4 = np.random.rand(4, 4)
matriz_2x8 = matriz_4x4.reshape(2, 8)
print("\nMatriz 4x4 original:")
print(matriz_4x4)
print("\nMatriz redimensionada 2x8:")
print(matriz_2x8)


Matriz 4x4 original:
[[0.26645075 0.42558529 0.79824917 0.99994253]
 [0.56816998 0.55443027 0.34744379 0.39289485]
 [0.70203462 0.05467332 0.63456155 0.52037206]
 [0.19667866 0.49605948 0.50518169 0.41674046]]

Matriz redimensionada 2x8:
[[0.26645075 0.42558529 0.79824917 0.99994253 0.56816998 0.55443027
  0.34744379 0.39289485]
 [0.70203462 0.05467332 0.63456155 0.52037206 0.19667866 0.49605948
  0.50518169 0.41674046]]


1.4

In [5]:
array_10 = np.linspace(0, 1, 10)
print("\nArray de 10 números equidistantes entre 0 y 1:")
print(array_10)


Array de 10 números equidistantes entre 0 y 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


1.5

In [6]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Concatenación horizontal (1D)
concat_horizontal = np.concatenate((v1, v2))
print("\nConcatenación horizontal:")
print(concat_horizontal)

# Concatenación vertical (convertir vectores a 2D)
v1_2d = v1.reshape(1, -1)
v2_2d = v2.reshape(1, -1)
concat_vertical = np.concatenate((v1_2d, v2_2d), axis=0)
print("\nConcatenación vertical:")
print(concat_vertical)


Concatenación horizontal:
[1 2 3 4 5 6]

Concatenación vertical:
[[1 2 3]
 [4 5 6]]


EJERCICIO 02: Resolver las siguientes operaciones:
Calcula la suma, resta, multiplicación y división de dos vectores.
Calcula la media, mediana y desviación estándar de un vector.
Normaliza un vector dividiendo cada elemento por el valor máximo.
Encuentra el índice del valor máximo y mínimo en un vector.
Realiza una multiplicación matricial entre dos matrices 3x3.

2.1

In [7]:
import numpy as np

v1 = np.array([10, 20, 30, 40, 50])
v2 = np.array([2, 4, 6, 8, 10])

print("Suma:", v1 + v2)
print("Resta:", v1 - v2)
print("Multiplicación:", v1 * v2)
print("División:", v1 / v2)

Suma: [12 24 36 48 60]
Resta: [ 8 16 24 32 40]
Multiplicación: [ 20  80 180 320 500]
División: [5. 5. 5. 5. 5.]


2.2

In [8]:
print("Media:", np.mean(v1))
print("Mediana:", np.median(v1))
print("Desviación estándar:", np.std(v1))

Media: 30.0
Mediana: 30.0
Desviación estándar: 14.142135623730951


2.3

In [9]:
v_norm = v1 / np.max(v1)
print("Vector normalizado:", v_norm)

Vector normalizado: [0.2 0.4 0.6 0.8 1. ]


2.4

In [10]:
print("Índice máximo:", np.argmax(v1))
print("Índice mínimo:", np.argmin(v1))

Índice máximo: 4
Índice mínimo: 0


2.5

In [11]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
m2 = np.array([[9, 8, 7],
               [6, 5, 4],
               [3, 2, 1]])

producto = np.matmul(m1, m2)
print("Multiplicación matricial:\n", producto)

Multiplicación matricial:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


EJERCICIO 03: Resolver con numpy los siguientes casos:
Selecciona los elementos pares de un vector de números enteros.
Filtra los valores mayores que 5 en un vector
Filtra los valores iguales a cero
Filtra los valores negativos
Aplicar la media a los valores mayores de 50.


3.1

In [12]:
import numpy as np
vector = np.array([0, 2, 3, 4, 6, 7, 8, 10, 12, 15, 50, 60, 70, -5, -10, 0])
pares = vector[vector % 2 == 0]
print("Elementos pares:", pares)

Elementos pares: [  0   2   4   6   8  10  12  50  60  70 -10   0]


3.2

In [13]:
mayores_5 = vector[vector > 5]
print("Valores mayores que 5:", mayores_5)

Valores mayores que 5: [ 6  7  8 10 12 15 50 60 70]


3.3

In [14]:
iguales_cero = vector[vector == 0]
print("Valores iguales a cero:", iguales_cero)

Valores iguales a cero: [0 0]


3.4

In [15]:
negativos = vector[vector < 0]
print("Valores negativos:", negativos)

Valores negativos: [ -5 -10]


3.5

In [16]:
mayores_50 = vector[vector > 50]
media_mayores_50 = np.mean(mayores_50) if mayores_50.size > 0 else None
print("Media de valores mayores que 50:", media_mayores_50)

Media de valores mayores que 50: 65.0


EJERCICIO 04: 4. Resolver con numpy los siguientes casos:
Crea un vector de 10 elementos y reemplaza todos los valores mayores que 5 con 0.
• Combina dos vectores booleanos utilizando las operaciones & (AND) y | (OR).
• Cuenta la cantidad de valores en un vector que son múltiplos de 3.
• Encuentra los índices de los elementos no nulos en un vector. (np.nonzero) Comprueba si todos los elementos en un array son mayores que un valor específico digitado por el usuario.

4.1

In [17]:
import numpy as np

v = np.array([1, 6, 3, 8, 5, 10, 2, 7, 4, 9])
v[v > 5] = 0
print("Vector con valores > 5 reemplazados por 0:")
print(v)

Vector con valores > 5 reemplazados por 0:
[1 0 3 0 5 0 2 0 4 0]


4.2

In [18]:
b1 = np.array([True, False, True, False])
b2 = np.array([True, True, False, False])

print("AND:", b1 & b2)
print("OR:", b1 | b2)

AND: [ True False False False]
OR: [ True  True  True False]


4.3

In [19]:
v2 = np.array([3, 6, 7, 9, 10, 12, 14, 15])
cantidad_multiplos_3 = np.sum(v2 % 3 == 0)
print("Cantidad de múltiplos de 3:", cantidad_multiplos_3)

Cantidad de múltiplos de 3: 5


4.4

In [20]:
v3 = np.array([0, 1, 2, 0, 3, 0])
indices_no_nulos = np.nonzero(v3)[0]
print("Índices de elementos no nulos:", indices_no_nulos)

Índices de elementos no nulos: [1 2 4]


4.5

In [21]:
valor = float(input("Introduce un valor para comparar: "))
arr = np.array([10, 15, 20, 25, 30])
todos_mayores = np.all(arr > valor)
print(f"¿Todos los elementos son mayores que {valor}? {todos_mayores}")

Introduce un valor para comparar: 90
¿Todos los elementos son mayores que 90.0? False


EJERCICIO 05: 5. Resolver con numpy los siguientes casos:
Calcula el cuadrado de cada elemento en un vector.
• Utiliza la función exponencial para elevar todos los elementos de un vector a la misma potencia.
• Encuentra los valores máximos y mínimos en cada fila de una matriz.
• Aplica la función sin a todos los elementos de un vector y almacena los resultados en otro vector.
• Realiza la transpuesta de una matriz 3x4.

5.1

In [22]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])
cuadrado = v ** 2
print("Cuadrado de cada elemento:", cuadrado)

Cuadrado de cada elemento: [ 1  4  9 16 25]


5.2

In [23]:
potencia = 3
exp_potencia = np.power(v, potencia)
print(f"Vector elevado a la potencia {potencia}:", exp_potencia)

Vector elevado a la potencia 3: [  1   8  27  64 125]


5.3

In [24]:
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

maximos_filas = np.max(m, axis=1)
minimos_filas = np.min(m, axis=1)

print("Máximos por fila:", maximos_filas)
print("Mínimos por fila:", minimos_filas)

Máximos por fila: [ 4  8 12]
Mínimos por fila: [1 5 9]


5.4

In [25]:
seno = np.sin(v)
print("Seno de cada elemento:", seno)

Seno de cada elemento: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


5.5

In [26]:
transpuesta = m.T
print("Matriz transpuesta (4x3):\n", transpuesta)


Matriz transpuesta (4x3):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Crea un DataFrame con las siguientes columnas: 'Nombre', 'Edad', 'Ciudad'. Añade al menos 10 registros.
• Del DataFrame creado, filtra a las personas que tienen más de 25 años. • A tu DataFrame, añade una nueva columna llamada 'Ingresos', rellénala con cualquier valor.
• Encuentra el promedio de la edad en tu DataFrame.
• Cuenta cuántas veces aparece cada ciudad en tu DataFrame.
• Agrupa tu DataFrame por 'Ciudad' y calcula el promedio de 'Edad' para cada ciudad. (groupby)
• Ordena tu DataFrame por 'Edad', de manera ascendente y luego descendente.

6.1

In [27]:
import pandas as pd

# Crear DataFrame
data = {'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Jorge', 'Elena', 'Pedro', 'Sofía', 'Raúl', 'Lucía'],
        'Edad': [23, 34, 29, 21, 40, 27, 33, 22, 30, 26],
        'Ciudad': ['Lima', 'Cusco', 'Lima', 'Arequipa', 'Cusco', 'Lima', 'Arequipa', 'Cusco', 'Lima', 'Arequipa']}

df = pd.DataFrame(data)

# Filtrar personas con edad mayor a 25
mayores_25 = df[df['Edad'] > 25]
print("Personas con más de 25 años:\n", mayores_25)


Personas con más de 25 años:
    Nombre  Edad    Ciudad
1    Luis    34     Cusco
2  Carlos    29      Lima
4   Jorge    40     Cusco
5   Elena    27      Lima
6   Pedro    33  Arequipa
8    Raúl    30      Lima
9   Lucía    26  Arequipa


6.2

In [28]:
df['Ingresos'] = [1500, 2000, 1800, 1200, 2200, 1600, 1700, 1300, 1900, 1400]
print("DataFrame con columna 'Ingresos':\n", df)

DataFrame con columna 'Ingresos':
    Nombre  Edad    Ciudad  Ingresos
0     Ana    23      Lima      1500
1    Luis    34     Cusco      2000
2  Carlos    29      Lima      1800
3   Marta    21  Arequipa      1200
4   Jorge    40     Cusco      2200
5   Elena    27      Lima      1600
6   Pedro    33  Arequipa      1700
7   Sofía    22     Cusco      1300
8    Raúl    30      Lima      1900
9   Lucía    26  Arequipa      1400


6.3

In [29]:
promedio_edad = df['Edad'].mean()
print("Promedio de edad:", promedio_edad)

Promedio de edad: 28.5


6.4

In [30]:
conteo_ciudades = df['Ciudad'].value_counts()
print("Cantidad por ciudad:\n", conteo_ciudades)


Cantidad por ciudad:
 Ciudad
Lima        4
Cusco       3
Arequipa    3
Name: count, dtype: int64


6.5

In [31]:
promedio_por_ciudad = df.groupby('Ciudad')['Edad'].mean()
print("Promedio de edad por ciudad:\n", promedio_por_ciudad)


Promedio de edad por ciudad:
 Ciudad
Arequipa    26.666667
Cusco       32.000000
Lima        27.250000
Name: Edad, dtype: float64


6.6

In [32]:
orden_asc = df.sort_values(by='Edad')
print("Ordenado por edad (ascendente):\n", orden_asc)

orden_desc = df.sort_values(by='Edad', ascending=False)
print("Ordenado por edad (descendente):\n", orden_desc)


Ordenado por edad (ascendente):
    Nombre  Edad    Ciudad  Ingresos
3   Marta    21  Arequipa      1200
7   Sofía    22     Cusco      1300
0     Ana    23      Lima      1500
9   Lucía    26  Arequipa      1400
5   Elena    27      Lima      1600
2  Carlos    29      Lima      1800
8    Raúl    30      Lima      1900
6   Pedro    33  Arequipa      1700
1    Luis    34     Cusco      2000
4   Jorge    40     Cusco      2200
Ordenado por edad (descendente):
    Nombre  Edad    Ciudad  Ingresos
4   Jorge    40     Cusco      2200
1    Luis    34     Cusco      2000
6   Pedro    33  Arequipa      1700
8    Raúl    30      Lima      1900
2  Carlos    29      Lima      1800
5   Elena    27      Lima      1600
9   Lucía    26  Arequipa      1400
0     Ana    23      Lima      1500
7   Sofía    22     Cusco      1300
3   Marta    21  Arequipa      1200


EJERCICIO 07: Del archivo adjunto realizar los siguientes filtros:
• Indicar cuantos son de la carrera de Ing. en sistemas
• Indicar cuantos son de la carrera de Ing. en derecho
• Indicar cuantos se inscribieron en el año 2015
• Indicar cuantos son del 1 y 2 semestre

In [41]:
import pandas as pd
import numpy as np

# Leer el archivo Excel usando pandas
df = pd.read_excel('/content/universidad.xlsx')

# Convertir la columna de inscripción a datetime para extraer el año
df['Inscripción'] = pd.to_datetime(df['Inscripción'], format='%d/%m/%Y')
df['Año_Inscripción'] = df['Inscripción'].dt.year

print("FILTROS SOLICITADOS:")
print("=" * 40)

# 1. Cuántos son de la carrera de Ing. en sistemas
ing_sistemas_df = df[df['Carrera'] == 'Ing. en sistemas']
ing_sistemas = len(ing_sistemas_df)
print(f"• Ing. en sistemas: {ing_sistemas}")
print("Datos completos:")
print(ing_sistemas_df)
print()

# 2. Cuántos son de la carrera de Ing. en derecho
ing_derecho_df = df[df['Carrera'] == 'Ing. en derecho']
ing_derecho = len(ing_derecho_df)
print(f"• Ing. en derecho: {ing_derecho}")
print("Datos completos:")
print(ing_derecho_df if not ing_derecho_df.empty else "No hay estudiantes de esta carrera")
print()

# 3. Cuántos se inscribieron en el año 2015
inscritos_2015_df = df[df['Año_Inscripción'] == 2015]
inscritos_2015 = len(inscritos_2015_df)
print(f"• Inscritos en 2015: {inscritos_2015}")
print("Datos completos:")
print(inscritos_2015_df)
print()

# 4. Cuántos son del 1 y 2 semestre
semestre_1_2_df = df[df['Semestre'].isin([1, 2])]
semestre_1_2 = len(semestre_1_2_df)
print(f"• Semestre 1 y 2: {semestre_1_2}")
print("Datos completos:")
print(semestre_1_2_df)

# Usando numpy para verificar resultados
print("\nVerificación con NumPy:")
print("=" * 40)
carreras = df['Carrera'].values
semestres = df['Semestre'].values
años = df['Año_Inscripción'].values

print(f"• Ing. en sistemas: {np.sum(carreras == 'Ing. en sistemas')}")
print(f"• Ing. en derecho: {np.sum(carreras == 'Ing. en derecho')}")
print(f"• Inscritos en 2015: {np.sum(años == 2015)}")
print(f"• Semestre 1 y 2: {np.sum((semestres == 1) | (semestres == 2))}")

FILTROS SOLICITADOS:
• Ing. en sistemas: 13
Datos completos:
   Num Control           Carrera  Semestre Inscripción  Id Persona  \
3     WiVaLó04  Ing. en sistemas         2  2016-12-03           4   
9     BePaNa10  Ing. en sistemas         9  2018-05-15          10   
21    ArLaOc22  Ing. en sistemas         1  2015-12-17          22   
24    JaSoAy25  Ing. en sistemas         2  2018-05-21          25   
26    DoAlVi27  Ing. en sistemas         4  2016-05-16          27   
31    JuNúHi32  Ing. en sistemas         4  2016-05-22          32   
45    TeLaKa46  Ing. en sistemas         4  2017-12-20          46   
55    ViSaDu56  Ing. en sistemas         1  2017-12-22          56   
73    LiToVe74  Ing. en sistemas         8  2015-12-12          74   
82    FrViVa83  Ing. en sistemas         4  2016-12-12          83   
89    LuÁvAl90  Ing. en sistemas         6  2017-12-19          90   
91    FéVaRo92  Ing. en sistemas         6  2018-05-02          92   
93    ArMuNi94  Ing. en siste